<a href="https://colab.research.google.com/github/FelipeGonzalezGarrido/Coding-Dojo/blob/main/Copia_de_Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [2]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [4]:
distance = np.array([100, 200, 400, 800, 1500, 3000, 5000, 10000])
print(distance)

[  100   200   400   800  1500  3000  5000 10000]


3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [8]:
print(f"Min: {np.min(distance)}")
print(f"Max: {np.max(distance)}")

Min: 100
Max: 10000


4) To find the average distance, use the np.mean() function

In [10]:
print(f"Average: {np.mean(distance)}")

Average: 2625.0


5) use the np.sum() function to find the total distance

In [11]:
print(f"Sum: {np.sum(distance)}")

Sum: 21000


6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [16]:
print(distance)
print(np.cumsum(distance))

[  100   200   400   800  1500  3000  5000 10000]
[  100   300   700  1500  3000  6000 11000 21000]


7) To round all of the values in an array, use np.round()

In [19]:
print(f" Round: {np.round(distance)}")

 Round: [  100   200   400   800  1500  3000  5000 10000]


8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [22]:
time = np.array([10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45])
print(time)

[  10.62   21.34   48.25  113.43  233.96  506.53  866.17 1757.45]


9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [23]:
speed = distance / time
print(speed)

[9.41619586 9.37207123 8.29015544 7.0528079  6.41135237 5.92265019
 5.77253888 5.69006231]


10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [51]:
HumanSpeedMPH = (speed * 0.00062) * 3600

print(f" Tiempo en segundos: {time}")
print(f" Distancia en metros: {distance}")
print(f" Velocidad en m/s: {speed.round(2)}")
print(f" Velocidad en Mph: {HumanSpeedMPH.round(2)}")
print(f" Humans are {75 - HumanSpeedMPH.round(2)} MPH Slower than a cheetah")
print(f" On average, humans perform {70 - np.mean(HumanSpeedMPH).round(2)} MPH slower than a cheetah")


 Tiempo en segundos: [  10.62   21.34   48.25  113.43  233.96  506.53  866.17 1757.45]
 Distancia en metros: [  100   200   400   800  1500  3000  5000 10000]
 Velocidad en m/s: [9.42 9.37 8.29 7.05 6.41 5.92 5.77 5.69]
 Velocidad en Mph: [21.02 20.92 18.5  15.74 14.31 13.22 12.88 12.7 ]
 Humans are [53.98 54.08 56.5  59.26 60.69 61.78 62.12 62.3 ] MPH Slower than a cheetah
 On average, humans perform 53.84 MPH slower than a cheetah
