<a href="https://colab.research.google.com/github/FelipeGonzalezGarrido/Coding-Dojo/blob/main/1.%20Data%20Science%20Fundamentals/Semana_1_Panaderia(Core).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduccion a numpy

## Tarea

se busca vender pasteles y recaudar $200


Lista de precios

brownies: 2

galletas: 1

pasteles: 10

In [1]:
# Lista de precios
price = [2,1,10]
type(price)


list

In [2]:
#Lista de cantidad
quantity_sold = [17,40,1]
type(quantity_sold)

list

Para buscar el dinero recaudado se puede multiplicar cada tipo de elemento

In [3]:
productos = ["brownies","galletas","pasteles"]

In [4]:
for x in range(len(price)):
    print(f"el valor de {productos[x]} vendidos es: $ {price[x] * quantity_sold[x]}")


el valor de brownies vendidos es: $ 34
el valor de galletas vendidos es: $ 40
el valor de pasteles vendidos es: $ 10


## Otra forma de hacer esto es importando Numpy

In [ ]:
import numpy as np

In [ ]:
price_array = np.array(price) # se crea array con nombre de lista_array
quantity_sold_array = np.array(quantity_sold)
type(price_array)# esta conversion de lista a array se llama numpy.ndarray - donde n es la dimension

numpy.ndarray

In [ ]:
price_array * quantity_sold_array # a diferencia de las listas. 
                                  #los arrays pueden ser sumados entre si, mientras tengan la misma cantidad de elementos.

array([34, 40, 10])

Para calcular la ganancia de cada venta se debe restar el costo de produccion de cada elemento.
para esto se creara un array con numpy.

In [ ]:
cost_array = np.array([0.25, 0.50, 5.00]) # en lugar de crear una lista y convertirla. aca se crea directamente como array

In [ ]:
profit_array = price_array - cost_array #para obtener la ganancia se resta el costo de produccion al precio de venta
print(profit_array) #es decir por cada brownie, galleta o pastel se gana 1.75, 0.5 y 5 respectivamente.

[1.75 0.5  5.  ]


Booleanos elementwise

Para saber que elementos obtuvieron un beneficio superior a 2 se puede utilizar el tipo de dato booleano
el cual, segun elementwise (misma ubicacion de valor en arrays a procesar) dira True o False segun corresponda.

In [ ]:
profit_array > 2.00

array([False, False,  True])

## Anadir, eliminar y reemplazar elementos en un array de NumPy

### Adicion.

tambien se busca vender tartas por $7, por lo que se tendra que actualizar el array de precios.

In [ ]:
#price_array = price_array + [7]  de esta forma, se suma el valor indicado a cada elemento del array.
#price_array = price_array - [7] asi, con esto se corrige lo hecho anteriormente.
print(price_array)

[ 2  1 10]


In [ ]:
price_array = np.append(price_array,7)# al igual que una lista, se utiliza el metodo append para aniadir un valor al array
print(price_array)

[ 2  1 10  7]


### Adicion de multiples valores en una linea.

tambien se busca agregar otros productos.

dulces: 4.50 - magdalenas: 3  - pan_de_platano:4  - torta=9

In [ ]:
price_array = np.append(price, [7, 4.50, 3, 4, 9])
print(price_array) # el resultado se muestra como decimal para acomodar al valor 4.50 del array
print(price_array.dtype) # mostrara el type de dato almacenado en array

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]
float64


### Eliminar

En este caso, se busca eliminar el valor de la torta. lo cual se realiza con el comando np.delete().
al igual que una lista, el array utiliza la indexacion. partiendo del 0 y donde el ultimo es -1.

In [ ]:
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


### Reemplazar - Actualizar
Se busca tambien actualizar el precio de los pasteles de 10 a 12.

esto mediante el indice del elemento.


In [ ]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


actualizar el quantity_sold_array para incluir la venta de 2 tartas, 3 bandejas de dulces, 
16 magdalenas y 5 panes de platano. una galleta vendida en realidad se cayo. 40 pasa a ser 39

In [ ]:
print(quantity_sold_array)# pre-validacion de objetos vendidos 

[17 40  1]


In [ ]:
quantity_sold_array = np.append(quantity_sold_array,[2,3,16,5]) # se adicionan objetos vendidos
quantity_sold_array[1] = 39 # se corrige galleta caida
print(quantity_sold_array)# validacion

[17 39  1  2  3 16  5]


In [ ]:
total_array = quantity_sold_array * price_array
print(f"cada elemento vendio: {total_array}")
print(f"el total recaudado fue: {total_array.sum()}")

cada elemento vendio: [34.  39.  12.  14.  13.5 48.  20. ]
el total recaudado fue: 180.5


In [ ]:
quantity_leftover_array = np.array([0,0,2,1,6,0,2])# se debe identificar con 0 los productos vendidos para mantener 
print(quantity_leftover_array) #la misma cantidad de elementos entre los array y asi poder calcularlos entre si

[0 0 2 1 6 0 2]


In [ ]:
sale_array = (price_array * 0.5) * quantity_leftover_array # para vender a la mitad se multiplica el valor por 0.5
total_sold = sale_array + total_array
print(f" suma de objetos vendidos en liquidacion: ${sale_array.sum()}")
print(f" suma de ventas hechas, incluyendo liquidacion: ${total_sold.sum()}")


 suma de objetos vendidos en liquidacion: $33.0
 suma de ventas hechas, incluyendo liquidacion: $213.5
